---
title: "Day 1 mini-project"
author: "By Anonymous Analyst Extraordinaire"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: united
---

```{r}

# INSTRUCTIONS

# You are a seasoned data scientist who has just arrived in Boston. You're looking to go see the sights, but you don't know where they are! Instead of buying a tourist guide like a Muggle, you are going to use your skills in exploratory data analysis and visualization to identify some of the cool spots to visit. 

# Working with your partner, conduct analyses to identify at least THREE cool spots that you want to check out. Use the dashboard format to communicate your findings. You can check e.g. on Google to confirm your findings, but you should include clear commentary indicating how your analysis supports your findings. I've included some of the code from the script we worked on together to help you get started. 

```

```{r}
# You may find the following resources useful: 
# - Your team member(s)! 
# - Data wrangling [cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf), 
# - `R` graphics [cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf), 
# - [`R` Graphics Cookbook](http://www.cookbook-r.com/Graphs/)
# - [RMarkdown Cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
```

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
```

```{r data_prep}
# put your data preparation code here. To get you started, the data preparation we performed in the session previously has already been pasted in. Feel free to add any additional data preparation code needed for your visualizations

listings <- read_csv('../../data/listings.csv')
calendar <- read_csv('../../data/calendar.csv')

source("clean_prices.R")
listings <- clean_prices(listings)
calendar <- clean_prices(calendar)
```

# A First Tab

Column {data-width=650}
-----------------------------------------------------------------------

###  Neighbourhood with highest occupancy rate over Summer

```{r box_1}

neighbourhood_lookup <- listings %>% 
	select(id, neighbourhood)

calendar %>% 
	left_join(neighbourhood_lookup, by = c('listing_id' = 'id')) %>% 
  mutate(month = month(date, label = TRUE)) %>% 
  filter(month == 'Aug' || month == 'Jun' || month == 'Jul' ) %>% 
	group_by(neighbourhood) %>% 
  summarize(n = n(), occupied = sum(!available), occupancy_rate =  (occupied/n)*100) %>% 
  filter(n>10000) %>% 
  arrange(desc(occupancy_rate)) %>% 
  ggplot() +
  aes(x=reorder(neighbourhood,occupancy_rate), y = occupancy_rate) +
  geom_bar(stat='identity') +
  coord_flip() +
  xlab('neighbourhood') +
  ylab('Occupancy Rate over Summer')


```

Column {data-width=350}
-----------------------------------------------------------------------

### Neighbourhood with highest occupancy rate

```{r box_2}
neighbourhood_lookup <- listings %>% 
	select(id, neighbourhood)

calendar %>% 
	left_join(neighbourhood_lookup, by = c('listing_id' = 'id')) %>% 
	group_by(neighbourhood) %>% 
  summarize(n = n(), occupied = sum(!available), occupancy_rate =  (occupied/n)*100) %>% 
  arrange(desc(occupancy_rate)) %>% 
  ggplot() +
  aes(x=reorder(neighbourhood,occupancy_rate), y = occupancy_rate) +
  geom_bar(stat='identity') +
  coord_flip() +
  xlab('neighbourhood') +
  ylab('Occupancy Rate')
  



```

### Neighbourhood with highest price over Summer

```{r box_3}
# Put the code for a supporting visualization here. This visualization should add context and nuance, but expect the main visualization to convey the bulk of your message. 

# This is not a good visualization -- always remember to include titles and legends. Make yours better! 

listings_sort<-listings %>%
  select(id,neighbourhood)

calendar %>% 
  left_join(listings_sort,by=c('listing_id'='id')) %>%
  mutate(month=month(date,label=TRUE)) %>%
  mutate(is_summer=(month=="Jun" || month=="Jul" || month =="Aug")) %>%
  filter(is_summer==TRUE)%>%
  group_by(neighbourhood)%>%
  summarise(ave_price=mean(price))%>%
  ggplot()+
  aes(x=reorder(neighbourhood,ave_price),y=ave_price)+
  geom_bar(stat="identity")+
  coord_flip()+
  labs(x="Average Price over Summer",y="neighbourhood")
```


# A Second Tab


Column {data-width=650}
-----------------------------------------------------------------------

### Box 1

Your dashboard is allowed to have multiple tabs! Only use it if you need it. 

Column {data-width=350}
-----------------------------------------------------------------------

### Box 2

